database:
  type: sqlite
  rebuild: False
  dataset_path: datasets/wikicorpus
  database_path: qatask/database/wikipedia_db/wikisqlite.db # Path to the database file
  preprocess: qatask/preprocess/dummy.py
  num_workers: 32
reader: 
  type: ensemble
  weighted_mu: 0.5
  sieve_threshold: 50
  model_checkpoint: nguyenvulebinh/vi-mrc-large
  batch_size: 300
  logpth: "logs/"
retriever:
  type: bm25
  top_k: 50
  index_path: checkpoint/indexes/BM25
postprocessor:
  type: default
  top_k: 500
  denoisy: 5
  concat_threshold: 0.15
  database_path: qatask/database/wikipedia_db/wikisqlite_post.db 
  index_path: checkpoint/indexes/BM25_post
pipeline:
  type: default
tokenizer:
  type: vnm
